#
# https://github.com/P3TERX/aria2.conf
# File name：script.conf
# Description: Aria2 additional function script configuration file
# Version: 2021.05.23
#

## Rclone upload settings (upload.sh) ##

# Rclone drive name
drive-name=onedrive

# Rclone drive directory
drive-dir=/aria2-downloads

# Upload log path
upload-log=/root/.aria2c/upload.log


## File cleanup settings (clean.sh & delete.sh) ##

# Delete .aria2 file after download is complete
delete-dot-aria2=true

# Delete .torrent file after download is complete (normal | enhanced | true | false)
# normal: Delete the .torrent file matching the infoHash.
# enhanced: Delete all .torrent files in the download directory that are not in the session file.
# true: normal + enhanced
delete-dot-torrent=true

# Delete empty directory after file moved or deleted
delete-empty-dir=true

# Delete files on task removal
delete-on-removed=true

# Delete files on download error
delete-on-error=true

# Delete files on unknown task status (force removed)
delete-on-unknown=true


## Advanced cleanup settings ##

# Min file size to keep (e.g. 10M). Smaller files will be deleted.
min-size=

# Include file extension (e.g. mp4,mkv). Others will be deleted.
include-file=

# Exclude file extension (e.g. txt,pdf).
exclude-file=

# Include file regex.
include-file-regex=

# Exclude file regex.
exclude-file-regex=
