name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
        crypto: [openssl, gnutls]
        bittorrent: [with-bt, without-bt]
        exclude:
        - os: macos-14
          crypto: gnutls
        - crypto: openssl
          bittorrent: without-bt

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
    - name: Cache dependencies
      uses: actions/cache@v5
      with:
        path: |
          /var/cache/apt
          ~/.brew
          /usr/local/lib/pkgconfig
        key: ${{ runner.os }}-build-${{ hashFiles('**/Makefile.am', 'configure.ac') }}
        restore-keys: |
          ${{ runner.os }}-build-
    - name: Linux setup
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install \
          clang-18 \
          lld-18 \
          libc++-18-dev \
          libc++abi-18-dev \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          pkg-config \
          libssl-dev \
          libgnutls28-dev \
          libc-ares-dev \
          zlib1g-dev \
          libsqlite3-dev \
          libssh2-1-dev \
          libcppunit-dev
    - name: MacOS setup
      if: runner.os == 'macOS'
      run: |
        brew install llvm@18 cppunit gettext openssl libssh2 c-ares sqlite3 \
          autoconf automake pkg-config libtool
    - name: Setup LLVM (Linux)
      if: runner.os == 'Linux'
      run: |
        echo 'CC=clang-18' >> $GITHUB_ENV
        echo 'CXX=clang++-18' >> $GITHUB_ENV
        echo 'LDFLAGS=-fuse-ld=lld-18' >> $GITHUB_ENV
    - name: Setup LLVM (MacOS)
      if: runner.os == 'macOS'
      run: |
        echo "CC=$(brew --prefix llvm@18)/bin/clang" >> $GITHUB_ENV
        echo "CXX=$(brew --prefix llvm@18)/bin/clang++" >> $GITHUB_ENV
        echo "LDFLAGS=-L$(brew --prefix llvm@18)/lib -Wl,-rpath,$(brew --prefix llvm@18)/lib" >> $GITHUB_ENV
    - name: Libtool
      run: |
        autoreconf -i
    - name: Setup compiler flags
      run: |
        asanflags="-fsanitize=address,undefined -fno-sanitize-recover=undefined"

        CPPFLAGS="$asanflags -g3"
        LDFLAGS="$asanflags"

        echo 'CPPFLAGS='"$CPPFLAGS" >> $GITHUB_ENV
        echo 'LDFLAGS='"$LDFLAGS" >> $GITHUB_ENV
    - name: Disable BitTorrent
      if: matrix.bittorrent == 'without-bt'
      run: |
        FEATURE_FLAGS="$FEATURE_FLAGS --disable-bittorrent"

        echo 'FEATURE_FLAGS='"$FEATURE_FLAGS" >> $GITHUB_ENV
    - name: Configure autotools (Linux, gnutls)
      if: runner.os == 'Linux' && matrix.crypto == 'gnutls'
      run: |
        ./configure --with-gnutls --without-openssl $FEATURE_FLAGS
    - name: Configure autotools (Linux, openssl)
      if: runner.os == 'Linux' && matrix.crypto == 'openssl'
      run: |
        ./configure --without-gnutls --with-openssl $FEATURE_FLAGS
    - name: Configure autotools (macOS)
      if: runner.os == 'macOS'
      run: |
        ./configure \
          --without-openssl --without-gnutls --with-appletls \
          --disable-nls
    - name: Build aria2
      run: |
        make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)" check
